---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-poc
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: Bertrand.Thomas@kirrk.com
    privateKeySecretRef:
      name: letsencrypt-poc
    solvers:
    - http01:
        ingress:
          class: nginx
